language: python
python:
    - "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - verilator
    - verilog
    - g++-4.9

install:
    # Convenience script for installing coreir on travis
    - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    - source install_coreir.sh
    
    # disable for now
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest-cov pytest-codestyle
    - pip install -e .

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    # Set env variables for genesis (installed earlier)
    - export GENESIS_HOME=`pwd`/Genesis2/Genesis2Tools
    - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
    - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB

script:
    - pytest --codestyle
             --cov canal
             --ignore=filecmp.py
             --ignore=Genesis2/
             -v --cov-report term-missing -s .


# disable coveralls for now
# after_success:
#    - coveralls
